### ISSUE TITLE
AssertionError on sqanti_qc2.py v4.0 and cDNA_Cupcake v8.5

### ISSUE THREAD

**Issue by huyuem** [Magdoll/SQANTI2#36] opened 2019-09-25 07:12 UTC
Hi Elizabeth,

I am running sqanti_qc2.py on version 4.0, use your example data to test and my commands are like this:
python sqanti_qc2.py -t 6 touse.rep.fasta gencode.v31.annotation.gtf hg38.genome.fa --cage_peak hg38.cage_peak_phase1and2combined_coord.bed

In my STDERR, I get this Error :

R scripting front-end version 3.4.4 (2018-03-15)
Cleaning up isoform IDs...
Cleaned up isoform fasta file written to: /home/hcd_lab/software/SQANTI2-master/example/touse.rep.renamed.fasta
[M::mm_idx_gen::42.906*1.75] collected minimizers
[M::mm_idx_gen::54.057*2.60] sorted minimizers
[M::main::54.057*2.60] loaded/built the index for 25 target sequence(s)
[M::mm_mapopt_update::56.513*2.53] mid_occ = 763
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 25
[M::mm_idx_stat::57.933*2.49] distinct minimizers: 167178949 (35.44% are singletons); average occurrences: 6.015; average spacing: 3.071
[M::worker_pipeline::65.164*2.88] mapped 4730 sequences
[M::main] Version: 2.17-r954-dirty
[M::main] CMD: minimap2 -ax splice --secondary=no -C5 -uf -t 6 /media/huyueming/disk1/data/hg38/hg38.genome.fa /home/hcd_lab/software/SQANTI2-master/example/touse.rep.renamed.fasta
[M::main] Real time: 65.291 sec; CPU: 187.598 sec; Peak RSS: 18.696 GB
output written to /home/hcd_lab/software/SQANTI2-master/example/touse.rep.renamed_corrected.fasta
**** Parsing Isoforms....
**** Running SQANTI...
**** Parsing provided files....
Reading genome fasta /media/huyueming/disk1/data/hg38/hg38.genome.fa....
****Aligning reads with Minimap2...
**** Predicting ORF sequences...
**** Parsing Reference Transcriptome....
Splice Junction Coverage files not provided.
**** Reading CAGE Peak data.
**** Performing Classification of Isoforms....
Number of classified isoforms: 4730
Traceback (most recent call last):
  File "/home/hcd_lab/software/SQANTI2-master/sqanti_qc2.py", line 1762, in <module>
    main()
  File "/home/hcd_lab/software/SQANTI2-master/sqanti_qc2.py", line 1758, in main
    run(args)
  File "/home/hcd_lab/software/SQANTI2-master/sqanti_qc2.py", line 1405, in run
    write_collapsed_GFF_with_CDS(isoforms_info, corrGTF, corrGTF+'.cds.gff')
  File "/home/hcd_lab/software/SQANTI2-master/sqanti_qc2.py", line 399, in write_collapsed_GFF_with_CDS
    for r in reader:
  File "/home/hcd_lab/software/anaconda2/lib/python2.7/site-packages/cupcake-8.5-py2.7-linux-x86_64.egg/cupcake/io/GFF.py", line 393, in next
    return self.read()
  File "/home/hcd_lab/software/anaconda2/lib/python2.7/site-packages/cupcake-8.5-py2.7-linux-x86_64.egg/cupcake/io/GFF.py", line 550, in read
    assert raw[2] == 'transcript'
AssertionError

**Comment by Magdoll** [comment] 2019-09-25 12:27
Hi @huyuem ,

Can you please upgrade to Cupcake v8.6 and SQANTI2 v4.1 and let me know if error persists? I've made some GFF changes and this could be the issue. Apologies.
-Liz

**Comment by arjeffries** [comment] 2019-09-29 19:59
Hi Liz,
Unfortunately I get the same error both on CentOS (upgraded SQANTI2) and a clean install on Ubuntu 18.04. Versions are below. R (&libraries) were installed via conda after the SQANTI2 and cDNA_cupcake install instructions.

SQANTI2 v4.1
cDNA_cupcake v8.7
R 3.5.1
openssl 1.0.2t
gffread 0.11.4 
ucsc-gtftogenepred 366
minimap2 2.17 

Thanks for any help you can give. Hopefully its just a dependency I'm missing. 
bw, Aaron

Error message: 

**** Performing Classification of Isoforms....
Number of classified isoforms: 54584
Traceback (most recent call last):
  File "/home/ubuntu/SQANTI2/sqanti_qc2.py", line 1793, in <module>
    main()
  File "/home/ubuntu/SQANTI2/sqanti_qc2.py", line 1789, in main
    run(args)
  File "/home/ubuntu/SQANTI2/sqanti_qc2.py", line 1436, in run
    write_collapsed_GFF_with_CDS(isoforms_info, corrGTF, corrGTF+'.cds.gff')
  File "/home/ubuntu/SQANTI2/sqanti_qc2.py", line 400, in write_collapsed_GFF_with_CDS
    for r in reader:
  File "/home/ubuntu/.conda/envs/sqanti2/lib/python2.7/site-packages/cupcake-8.6-py2.7-linux-x86_64.egg/cupcake/io/GFF.py", line 395, in next
    return self.read()
  File "/home/ubuntu/.conda/envs/sqanti2/lib/python2.7/site-packages/cupcake-8.6-py2.7-linux-x86_64.egg/cupcake/io/GFF.py", line 552, in read
    assert raw[2] == 'transcript'
AssertionError

**Comment by Magdoll** [comment] 2019-10-08 10:50
Hi,
For those following this issue I am unable to reproduce the error....
-Liz

**Comment by defendant602** [comment] 2019-10-28 09:33
It's because of the different gffread versions. Try to install the newest version of gffread and add to your PATH. Do not use gffread embedded in cufflinks.

**Comment by Magdoll** [comment] 2019-11-19 19:31
Closing unless otherwise noted.

**Closed as completed by Magdoll** 2019-11-19 19:31 UTC
